
```{r}
library(rvest)
library(tidyverse)
library(SwimmeR)
library(JumpeR)
library(sjmisc)
```

```{r}
# First three blocks are setting up the links from the timing company's pages, in this case Delta Timing.

url <- "http://results.deltatiming.com/"
selector <- "h4 a"

contents <- read_html(url)
links <- html_attr(html_nodes(contents, selector), "href")

links <- links[!links %>% str_detect("xc|rowing|canoe|usack|icf-cam|wwc|flotrack")]
school_pages <- links[links %>%
        str_detect("results.deltatiming")]
links <- links[!(links %in% school_pages)]

links <- ifelse(str_detect(links, "http"), paste0("", links), paste0("http://results.deltatiming.com", links))
links <- links[c(-1, -157)]
```

```{r}
html_fnx <- function(x, select) { html_session(x) %>%
    html_nodes(select) %>%
      html_attr("href")
    }
event_links <- map(links[1:298], html_fnx, "td a")
```

```{r}

event_links <- event_links %>%
  flatten() %>%
  map(str_remove, "/tf") 
event_links <- paste0("http://tfresultsdata.deltatiming.com", event_links, ".htm")

```


```{r}
#remove some high school meets

event_links <- event_links[!event_links %>%
              str_detect("hs")]
```

```{r}
# List of events and "R disciplines"

all_events <- paste0("(?i)", c("Shot put", "Discus", "Javelin", "Hammer", "Weight", "Long jump", "Triple jump", "High jump", "Pole vault", "100\\s*m", "200\\s*m", "\\B00\\s*m\\b", "400\\s*m", "800\\s*m", "1500\\s*m", "1 mile", "100\\s*m h", "110\\s*m hurdles", "400\\s*m h", "5\\,*000\\s*m", "10\\,*000\\s*m", "Steeplechase"), collapse = "|")

throw_horiz_jumps <-paste0("(?i)", c("Shot put", "Discus", "Javelin", "Hammer", "Weight", "Long jump", "Triple jump"))
vertical_jumps <- paste0("(?i)", c("High jump", "Pole vault"))
sprint_hurdle <- paste0("(?i)", c("100\\s*m", "200\\s*m", "60\\s*m", "400\\s*m", "100\\s*m hurdles", "110\\s*m hurdles", "400\\s*m hurdles"))
distance <- paste0("(?i)", c("800\\s*m", "1500\\s*m", "1 mile","5\\,*000\\s*m", "10\\,*000\\s*m", "Steeplechase"))

remove <- paste0(c("\n\\s*", "#\\s*(?=\\d{1,4})[0-9]*", "\\$", "Q|q", "=", "PR", "SB", "PB", "\\[", "\\]"), collapse = '|')

```

```{r}
# Helper / component functions 

# Generic cleaning of results - things that should be done / need to be done to all events from all sources

results_cleaner <- function (event_results) {

remove <- c("\n\\s*", "#\\s*(?=\\d{1,4})[0-9]*", "\\$", "Q|q", "=", "PR", "SB", "PB")
 
        
event_results <- event_results %>%
    str_remove_all(paste0(remove, collapse="|")) %>%
    tibble() %>%
    rename("event_results" = ".") %>%
    filter(!str_detect(event_results, "DNS")) %>%
    mutate(event_results = trimws(event_results))
 
return(event_results)

}

# Take full PDF of results and divide into dataframes for each event

pdf_cleaner <- function (pdf_input) {
  
 remove <- c("\n\\s*", "#\\s*(?=\\d{1,4})[0-9]*", "\\$", "Q|q", "=")

 meet_title <-trimws(pdf_input[1])
    
 pdf_clean <- pdf_input %>%
   str_remove_all(paste0(remove, collapse="|")) %>%
   tibble() %>%
   rename("event_results" = ".") %>%
   mutate(Event = case_when(
     str_detect(event_results, all_events) ~ event_results,
     str_detect(event_results, meet_title) ~ "Metadata"
  ))   %>%
   fill(Event) %>%
   filter(Event != "Metadata") %>%
   bind_rows() 
 
 event_dfs <- split(pdf_clean, pdf_clean$Event)
 
 return(event_dfs)
}


# Tidy throws and jumps (precursor to parsing out the wind for outdoor horizontal jumps)

horizontal_tidy <- function (event_results) {
 
event_results <- event_results %>%
    pivot_longer(cols = F1:F6, names_to = "Attempt", values_to = "Distance") %>%
    mutate(Attempt = as.factor(str_remove(Attempt, "F")))

return(event_results)

}

# Parse wind from jump distance for outdoor horizontal jumps

wind <- function (event_results) {

event_results <- event_results %>%
    mutate(Distance = str_remove(Distance, "\\)")) %>%
    separate(Distance, into = c("Distance", "Wind"), sep = "([\\( | \\s | \\+])") %>%
    mutate(Wind = ifelse(Wind == '', "0.0", Wind))  # obnoxious little necessary workaround because `separate` coerces 0.0 to blank (not NA, blank)

return(event_results)

}

# Isolate competitors' biographical info - full name, year and school / affiliation - from Flash Results' PDF's.

athlete_info <- function (result_line) {
   
  name <- trimws(str_match(result_line, "([A-Z].*)(\\sFR\\s|\\sSO\\s|\\sJR\\s|\\sSR\\s|\\sUN\\s|\\s{3})")[2])

  year <- trimws(str_extract(result_line, "(\\sFR\\s|\\sSO\\s|\\sJR\\s|\\sSR\\s|\\sUN\\s)"))

  school <- trimws(str_match(result_line, "(\\sFR\\s*|\\sSO\\s*|\\sJR\\s*|\\sSR\\s*|\\sUN\\s*)(.*?)([0-9]|\\sX)")[3])
  
  competitors <- c(name, year, school)
  return(competitors)
}

```


```{r}

# Situations needing to be addressed: 
  # Foul on the first jump / throw - sometimes it recognizes an X to start the results section, but not always
  # Names so long they go up to the first letter of Year

```

```{r}

# USE CASE: "TWO-LINE RESULTS" - Athlete's biographical info, their best mark (often in metric and standard) is on one line, and the field series is below

delta_throw <- read_results('http://tfresultsdata.deltatiming.com/2019-hurricane-invitational/190315F012.htm')

event <- str_match(delta_throw, all_events)
event <- event[!is.na(event)]

results <- delta_throw %>%
   str_remove_all(remove) 

single_line_results <- tibble(results) %>%
    mutate(ID = row_number()) %>%
    filter(ID >= min(which(str_starts(results, "1\\s*[A-Z]")))) %>%
    mutate(ID = row_number()) %>%
    mutate(numerical_data = ifelse((ID) %% 2 != 0, results[ID + 1], "drop")) %>%
    filter(numerical_data != "drop") %>%
    select(-ID) 

athletes <- single_line_results$results

athlete_cols <- map(athletes, athlete_info)
athlete_cols <- as.data.frame(do.call(rbind, athlete_cols))

colnames(athlete_cols) <- c("Athlete", "Year", "School")
athlete_cols <- filter(athlete_cols, Athlete != "NA")

numerical_data <- single_line_results$numerical_data
numerical_data <- tibble(numerical_data) %>%
   filter(str_starts(numerical_data, "([0-9]{1,2}\\.[0-9]{1,3})|X|FOUL")) %>%
   mutate(Tiebreak = str_extract(numerical_data, "[0-9]{1,2}\\.[0-9]{3}")) %>%
   mutate(numerical_data = str_remove(numerical_data, "([0-9]{1,2}\\.[0-9]{3})")) %>%
   separate(numerical_data, into = c("F1", "F2", "F3", "F4", "F5", "F6"), sep = "\\s+")

final_results <- bind_cols(athlete_cols, numerical_data)
final_results

```

```{r}

# USE CASE: SINGLE-LINE RESULTS - throws, horizontal jumps and sprints where the athlete's bio info and field series are straight across on a single line

athlete_info <- function (result_line) {
   
  name <- trimws(str_match(result_line, "([A-Z].*)(\\sFR\\s|\\sSO\\s|\\sJR\\s|\\sSR\\s|\\sUN\\s|\\s{2}[:alpha:]{3,})")[2])
  name <-trimws(str_remove(name, "\\sFR|\\sSO|\\sJR|\\sSR"))

  year <- trimws(str_extract(result_line, "(\\sFR\\s|\\sSO\\s|\\sJR\\s|\\sSR\\s|\\sUN\\s)"))

  school <- trimws(str_match(result_line, "(\\sFR\\s*|\\sSO\\s*|\\sJR\\s*|\\sSR\\s*|\\sUN\\s*|[:alpha:]\\s{2,})(.*?)([0-9]|\\sX)")[,3])
  
  competitors <- c(name, year, school)
  return(competitors)
}

# flash_sprint <- read_results('https://flashresults.com/2019_Meets/Outdoor/05-09_ACC/029-1.pdf')
flash_sprint <- read_results("https://www.flashresults.com/2019_Meets/Outdoor/04-27_VirginiaGrandPrix/029-1.pdf")
#flash_throw <- read_results('https://flashresults.com/2019_Meets/Outdoor/05-09_ACC/019-1.pdf')

event <- str_match(flash_sprint, all_events)
event <- event[!is.na(event)]

results <- flash_sprint %>%
   str_remove_all(remove) 

results <- results[(str_starts(results, "[0-9]{1,2}\\s+[A-Z]|Section") | str_detect(results, "Name"))]
new_cols <- unlist(str_split(results[1], "\\s+"))
event_results <- results[-1]

athlete_cols <-map(event_results, athlete_info)
athlete_cols <- as.data.frame(do.call(rbind, athlete_cols))

colnames(athlete_cols) <- c("Athlete", "Year", "School")
athlete_cols <- filter(athlete_cols, Athlete != "NA")

numerical_data <- trimws(str_extract_all(event_results, "[0-9]{1,2}\\..*"))
cols_to_countback <- str_split(numerical_data, "\\s+")
cols_to_countback <- round(mean(unlist(lapply(cols_to_countback[1:6], length))))
cols_to_add <- tail(new_cols, cols_to_countback)

cols_to_countback
cols_to_add

numerical_data <- tibble(numerical_data) %>%
   mutate(Tiebreak = str_extract(numerical_data, "[0-9]{1,2}\\.[0-9]{3}")) %>%
   mutate(numerical_data = str_remove(numerical_data, "([0-9]{1,2}\\.[0-9]{3})")) %>%
   separate(numerical_data, into = cols_to_add, sep = "\\s+")

final_results <- bind_cols(athlete_cols, numerical_data) 
# %>%
#    filter(V1 != "NA")

final_results
```

```{r}
# USE CASE: Sprints and hurdles in "long" / per section format - often has a combined listing / ranking at the end, which are in fact duplicates of what is in the per-section section

section_sprint <- read_results("http://tfresultsdata.deltatiming.com/2019-war-eagle-invitational/190419F001.htm")

results <- str_remove(section_sprint, remove)
results <- str_replace(results, "Unattached|Ghana", "UN Unattached") # Of course I choose a sample result with an international non-college athlete

results <- tibble(results) %>%
   mutate(section = str_extract(results, "Section\\s*[0-9]")) %>%
   mutate(wind = str_extract(results, "(\\+|\\-|\\s)[0-9]\\.[0-9]")) %>% # Section and Wind are given for each section, not per athlete, so we'll first pull them into a column and then two lines down fill in that data for each athlete
   fill(section, wind) %>%
   filter(str_starts(results, "[0-9]{1,2}\\s+[A-Z]"))

athlete_cols <-map(results$results, athlete_info)
athlete_cols <- as.data.frame(do.call(rbind, athlete_cols))

colnames(athlete_cols) <- c("Athlete", "Year", "School")
athlete_cols <- filter(athlete_cols, Athlete != "NA")

section_wind <- select(results, section, wind)
numerical_data <- trimws(str_extract_all(results$results, "[0-9]{1,2}\\..*"))
numerical_data <- tibble(numerical_data) %>%
   filter(str_starts(numerical_data, "([0-9]{1,2}\\.[0-9]{1,3})|X")) %>%
   mutate(Tiebreak = str_extract(numerical_data, "[0-9]{1,2}\\.[0-9]{3}")) %>%
   mutate(numerical_data = str_remove(numerical_data, "([0-9]{1,2}\\.[0-9]{3})")) 


athlete_cols %>%
   bind_cols(numerical_data, section_wind) %>%
   distinct(Athlete, .keep_all = TRUE)

```




```{r}

### EVERYTHING BELOW ARE ORIGINAL VERSIONS, SCRATCH PADS, ETC

```


```{r}


# Still looking for best way to clean-up "team rankings" when they are inserted via "=====" rows or maybe just the word(s) 'team' or 'rankings' or 'score'
# And how to deal with multiple flights on a results page

throw_jump <- function (event_results) {
  
 results <- results_cleaner(event_results)
   
 results <- results %>%
   mutate(ID = row_number()) %>%
   filter(ID >= min(which(str_starts(event_results, "1\\s*[A-Z]")))) %>%
   mutate(ID = row_number()) %>%
   mutate(results = (ifelse((ID) %% 2 != 0, event_results[ID + 1], "odd"))) %>%
   filter((ID) %% 2 != 0) %>%
   select(-ID) %>%
   mutate(event_results = str_replace_all(event_results, "[0-9+]", " ")) %>%
   mutate(event_results = str_replace(event_results, "..\\sm(.*)", "")) %>%
   mutate(results = str_replace_all(results, "m", "")) %>%
   separate(results, c("F1", "F2", "F3", "F4", "F5", "F6"),  "\\s{1,}") %>%
   rename("Athlete" = event_results) 
   #mutate(Event = event_name)

 results <- horizontal_tidy(results)
 
 results <- wind(results)
 
  return(results)
}

#throw_jump(throw_valid)

```

```{r}

vault_highjump <- function (event_results) {
   
results <- results_cleaner(event_results)   
   
results <-  results %>%
   mutate(event_results = trimws(event_results)) %>%
   mutate(ID = row_number()) %>%
   filter(ID >= min(which(str_starts(event_results, "1\\s*[A-Z]")))) %>%
   mutate(ID = row_number()) %>%
   mutate(heights = ifelse(str_starts(event_results, "[0-9]{1,2}\\s*[A-Z]"), event_results[ID + 1], "NA"), 
          results = ifelse(str_starts(event_results, "[0-9]{1,2}\\s*[A-Z]"), event_results[ID + 2], "NA")) %>%
   filter(heights != "NA" | results != "NA") %>%
   select(-ID) %>%
   mutate(event_results  = str_replace_all(event_results, "[0-9]", " ")) %>%
   mutate(event_results = str_replace_all(event_results, "..\\sm(.*)", ""))

 heights <- as.data.frame(str_split_fixed(results$heights, "\\s{1,}", 12))
 marks <- as.data.frame(str_split_fixed(results$results, "\\s{1,}", 12))
 
heights <- set_names(heights, paste0(colnames(heights), "_", "Bar")) 
marks <- set_names(marks, paste0(colnames(marks), "_", "Outcome")) 

# Tidy up! Because of the unusual arrangement of vertical jumps - fixed bar height progessions, 1-3 outcomes per height, open-ended number of bar heights - tidying is more than an academic exercise here. Anything other than a standard display of results requires the data to be tidy.

results %>%
   bind_cols(heights, marks) %>%
   select(-results, -heights) %>%
   pivot_longer(
      cols = !event_results,
      names_to = c("height", ".value"),
      names_sep = "_"
   ) %>%
   filter(Bar != "")

}

vault_highjump(event_results_trial)

```



```{r}
sprint_test %>%
   mutate(section = str_extract(event_results, "Section\\s*[0-9]")) %>%
   mutate(wind = str_extract(event_results, "(\\+|\\-|\\s)[0-9]\\.[0-9]"))  %>% # Section and Wind are given for each section, not per athlete, so we'll first pull them into a column and then two lines down fill in that data for each athlete
   filter(str_starts(event_results, "[0-9]{1,2}\\s+[A-Z]|Section")) %>%  # Keep only the rows we need
   fill(section, wind) %>%
   filter(!str_detect(event_results, "Section")) %>% # No longer need the rows with the Section and Wind info
   mutate(event_results =  str_replace_all(event_results, "^[0-9]\\s*", " ")) %>%
   mutate(time = str_extract(event_results, "[0-9].*")) %>%
   mutate(event_results = str_remove(event_results, "[0-9].*")) %>%
   rename(Name = event_results) %>%
   distinct(Name, .keep_all = TRUE)  # This gets rid of the "final" combined rankings at the bottom. We had to wait until this late to do it because we had to wait until their name & school were isolated for the values to be distinct (heaven forbid the same data be presented in the same way at the top and bottom)




```

```{r}

# Sprint / hurdles in "wide" format

#sprint_wide <- results_cleaner(sprint2)

sprint_wide <- sprint_test %>%
   mutate(ID = row_number()) %>%
   filter(ID >= min(which(str_detect(event_results, "Name|Athlete"))))  %>%
   select(-ID) %>%
   filter(str_starts(event_results, "[0-9]{1,2}\\s+[A-Z]|Section") | str_detect(event_results, "Name")) %>%
   mutate(event_results = str_replace(event_results, "Name", "FirstName LastName")) %>%
   mutate(event_results = str_replace(event_results, "^[0-9]{1,2}\\s*", " "))  %>%
   mutate(Tiebreak = str_extract(event_results, "[0-9]{1,2}\\.[0-9]{3}")) %>%    # Create a new column for when they need thousandths to determine placing
   mutate(event_results = str_trim(str_replace(event_results, "([0-9]{1,2}\\.[0-9]{3})", " ")))  %>%   # Remove the "tiebreak" from the original row / cell
   mutate(event_results = str_replace(event_results, "\\s([0-9])", "@\\1")) %>%     # Insert a separator between the text and the numbers
   separate(event_results, into = c("Words", "Numbers"), sep = "@") 
   
new_cols <- unlist(str_split(sprint_wide$Words[1], "\\s+"))    # Separate out the column headings from the original result sheet


sprint_wide <- sprint_wide[-1,] %>%
   filter(!str_detect(Numbers, "[a-zA-Z]+"))
sprint_wide

#numbers <- str_extract_all(sprint_wide$Numbers, "[0-9].*")  # Split the block of numbers into individual numbers
#numbers <- str_split(numbers, "\\s+")

#cols_to_countback <- length(numbers[[3]])    # The number of numerical values in the results - some will have seed times and some won't, some will have heat # and some won't, etc
#cols_to_add <- tail(new_cols, cols_to_countback)  # How many of the columns we'll need for the number of numerical values

#temp_df <- as.data.frame(do.call(rbind, numbers))
#colnames(temp_df) <- cols_to_add
#temp_df   # Create a dataframe of the numerical values, and slap the column headers atop them

#sprint_wide = sprint_wide[-1,]   # Remove the first row, which contained what are now the column headers
#sprint_wide %>%
 #  bind_cols(temp_df)

```

```{r}

# Single-line "wide" throws from a Flash PDF

flash <- read_results("https://flashresults.com/2019_Meets/Outdoor/05-09_ACC/029-1.pdf")
flash_pdf <- pdf_cleaner(flash)

flash_pdf <- flash_pdf[[1]]
#flash_pdf <-
   flash_pdf %>%
   mutate(ID = row_number()) %>%
   filter(ID >= min(which(str_detect(event_results, "Name|Athlete")))) %>%   
   select(-ID) %>%
   filter(str_starts(event_results, "[0-9]{1,2}\\s+[A-Z]|Section") | str_detect(event_results, "Name")) %>%
   mutate(event_results = str_replace(event_results, "Name", "FirstName LastName")) %>%
   mutate(event_results = str_replace(event_results, "^[0-9]{1,2}\\s*", " "))  %>%
   mutate(event_results = str_replace(event_results, "\\s([0-9]|X)", "@\\1")) %>%     # Insert a separator between the text and the numbers
   separate(event_results, into = c("Words", "Numbers"), sep = "@") %>%
   mutate(Numbers = trimws(str_remove(Numbers, "PB"))) 
   
   new_cols <- unlist(str_split(flash_pdf$Numbers[1], "\\s+"))    # Separate out the column headings from the original result sheet

flash_pdf <- flash_pdf[-1,] 

#flash_pdf <-   flash_pdf %>%
 #  separate(Numbers, into = paste("Flight", new_cols), sep = "\\s{1,}") %>%
  # select(1:7, Event)  %>%
#   filter(!is.na(`Flight 2`))
   

#flash_pdf

numbers <- str_extract_all(flash_pdf$Numbers, "[0-9].*|X.*")  # Split the block of numbers into individual numbers

numbers <- str_split(numbers, "\\s+")

for (i in seq_along((numbers))) {
   numbers[[i]] <- numbers[[i]][-1]
}


numbers <- numbers[lengths(numbers) > 1] # Eliminate team scores
temp_df <- as.data.frame(do.call(rbind, numbers))
#colnames(temp_df) <-new_cols
```
